### ISSUE TITLE
NSFoundationVersionNumber_iOS_7_1

### ISSUE THREAD

**Issue by love4soul** [romaonthego/RESideMenu#178]
Can't compile on xCode 5.1.1
Error:(290, 41) use of undeclared identifier 'NSFoundationVersionNumber_iOS_7_1'
