### ISSUE TITLE
'NSFoundationVersionNumber_iOS_7_1' not defined in iOS 7.1

### ISSUE THREAD

**Issue by peng90** [romaonthego/RESideMenu#181]
I got compiler error: Use of undeclared identifier 'NSFoundationVersionNumber_iOS_7_1' for the new build in Xcode 5.1.1 with base SDK set to iOS 7.1. 
We may want to use some other ways to test OS version just to support iOS 7.1
